version: '3'
services:     
  backend:
    image: "dineshsonachalam/aws-js-sdk-example:latest"
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    networks:
      - backend
    ports:
      - "5000:5000"
networks:
  backend: